
CREATE TABLE SBT_ID (
  
  Template_ID VARCHAR(50) NOT NULL,
  SMS_ID VARCHAR(50) NOT NULL,
  Vender VARCHAR(50)
 
);

INSERT INTO SBT_ID (Template_ID, SMS_ID, Vender) VALUES
  ('T123', 'SMS123', 'SBT'),
  ('T456', 'SMS456', 'SBT');
  
  